# Generated by Django 6.0.2 on 2026-02-18 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_payment_card_last_4_payment_transaction_id'),
        ('tenants', '0002_default_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tenant',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='Tienda'),
        ),
        migrations.AddField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='Tienda'),
        ),
    ]
