# Generated by Django 6.0.2 on 2026-02-18 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_make_tenant_nonnull'),
        ('tenants', '0002_default_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.branch', verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='order',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cajero'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_voided',
            field=models.BooleanField(default=False, verbose_name='Anulada'),
        ),
        migrations.AddField(
            model_name='order',
            name='iva_amount',
            field=models.IntegerField(default=0, verbose_name='IVA'),
        ),
        migrations.AddField(
            model_name='order',
            name='net_amount',
            field=models.IntegerField(default=0, verbose_name='Neto'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Nro. Boleta/Ticket'),
        ),
        migrations.AddField(
            model_name='order',
            name='void_reason',
            field=models.TextField(blank=True, verbose_name='Razón Anulación'),
        ),
        migrations.AddField(
            model_name='order',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cost_at_sale',
            field=models.IntegerField(default=0, verbose_name='Costo al momento de venta'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta (Redcompra)'), ('TRANSFER', 'Transferencia'), ('MIXED', 'Pago Mixto')], max_length=20),
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado el')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Caja')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registers', to='tenants.branch', verbose_name='Sucursal')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='Tienda')),
            ],
            options={
                'verbose_name': 'Caja Registradora',
                'verbose_name_plural': 'Cajas Registradoras',
                'unique_together': {('tenant', 'branch', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado el')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Apertura')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Cierre')),
                ('opening_cash', models.IntegerField(default=0, verbose_name='Efectivo Inicial (CLP)')),
                ('closing_cash', models.IntegerField(blank=True, null=True, verbose_name='Efectivo Final (CLP)')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Cajero')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='sales.cashregister', verbose_name='Caja')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='Tienda')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='sales.shift', verbose_name='Turno'),
        ),
    ]
