# Generated by Django 6.0.2 on 2026-02-16 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='pet_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='pet_type',
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='rut',
            field=models.CharField(max_length=12, unique=True, verbose_name='RUT Cliente'),
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado el')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Mascota')),
                ('species', models.CharField(max_length=50, verbose_name='Especie')),
                ('breed', models.CharField(blank=True, max_length=100, verbose_name='Raza')),
                ('age_years', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad (Años)')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
            },
        ),
    ]
