# Generated by Django 6.0.2 on 2026-02-18 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_pet_name_remove_customer_pet_type_and_more'),
        ('tenants', '0002_default_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='Tienda'),
        ),
        migrations.AddField(
            model_name='pet',
            name='tenant',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='Tienda'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='rut',
            field=models.CharField(max_length=12, verbose_name='RUT Cliente'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('tenant', 'rut')},
        ),
    ]
