# Generated by Django 6.0.2 on 2026-02-18 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_default_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado el')),
                ('role', models.CharField(choices=[('OWNER', 'Dueño'), ('ADMIN', 'Administrador'), ('SUPERVISOR', 'Supervisor'), ('CASHIER', 'Cajero')], default='CASHIER', max_length=20, verbose_name='Rol')),
                ('pin_code', models.CharField(blank=True, help_text='PIN de 4-6 dígitos para cambio rápido de cajero', max_length=6, verbose_name='PIN Rápido')),
                ('is_active_staff', models.BooleanField(default=True, verbose_name='Activo')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='tenants.branch', verbose_name='Sucursal Asignada')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='Tienda')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
                'unique_together': {('tenant', 'user')},
            },
        ),
    ]
