# Generated by Django 6.0.2 on 2026-02-18 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado el')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre Comercial')),
                ('legal_name', models.CharField(blank=True, max_length=300, verbose_name='Razón Social')),
                ('rut_empresa', models.CharField(max_length=12, unique=True, verbose_name='RUT Empresa')),
                ('subdomain', models.SlugField(max_length=63, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='tenants/logos/')),
                ('giro', models.CharField(blank=True, max_length=200, verbose_name='Giro Comercial')),
                ('direccion_legal', models.CharField(blank=True, max_length=300, verbose_name='Dirección Legal')),
                ('comuna', models.CharField(blank=True, max_length=100, verbose_name='Comuna')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Región')),
                ('iva_rate', models.DecimalField(decimal_places=2, default=19.0, max_digits=4, verbose_name='Tasa IVA (%)')),
                ('currency', models.CharField(default='CLP', max_length=3, verbose_name='Moneda')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tienda',
                'verbose_name_plural': 'Tiendas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado el')),
                ('plan', models.CharField(choices=[('FREE', 'Gratuito (1 sucursal, 1 caja)'), ('BASIC', 'Básico (2 sucursales, 3 cajas)'), ('PRO', 'Profesional (5 sucursales, 10 cajas)'), ('ENTERPRISE', 'Empresarial (ilimitado)')], default='FREE', max_length=20)),
                ('status', models.CharField(choices=[('TRIAL', 'Período de Prueba'), ('ACTIVE', 'Activa'), ('PAST_DUE', 'Pago Pendiente'), ('CANCELLED', 'Cancelada')], default='TRIAL', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin Período Prueba')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='Fin Período Actual')),
                ('max_branches', models.PositiveIntegerField(default=1, verbose_name='Máx. Sucursales')),
                ('max_registers', models.PositiveIntegerField(default=1, verbose_name='Máx. Cajas')),
                ('max_users', models.PositiveIntegerField(default=2, verbose_name='Máx. Usuarios')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado el')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre Sucursal')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('is_main', models.BooleanField(default=False, verbose_name='Sucursal Principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'unique_together': {('tenant', 'name')},
            },
        ),
    ]
