# Generated by Django 6.0.2 on 2026-02-16 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='price_clp',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_critical',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Generico', max_length=100, verbose_name='Marca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='is_bulk',
            field=models.BooleanField(default=False, verbose_name='Venta a Granel'),
        ),
        migrations.AddField(
            model_name='product',
            name='lifecycle',
            field=models.CharField(choices=[('PUPPY', 'Cachorro/Kitten'), ('ADULT', 'Adulto'), ('SENIOR', 'Senior'), ('ALL', 'Todas las Etapas')], default='ALL', max_length=10, verbose_name='Etapa de Vida'),
        ),
        migrations.AddField(
            model_name='product',
            name='species',
            field=models.CharField(choices=[('DOG', 'Perro'), ('CAT', 'Gato'), ('OTHER', 'Exótico/Otro')], default='DOG', max_length=10, verbose_name='Especie'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre Categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre Producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Stock Disponible'),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado el')),
                ('batch_number', models.CharField(max_length=50, verbose_name='N° Lote')),
                ('expiration_date', models.DateField(verbose_name='Fecha Vencimiento')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Cantidad Inicial')),
                ('current_quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Cantidad Actual')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
            },
        ),
        migrations.DeleteModel(
            name='StockMovement',
        ),
    ]
