# Generated by Django 6.0.2 on 2026-02-16 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado el')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado el')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de Barras')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('price', models.IntegerField(verbose_name='Precio Venta (CLP)')),
                ('cost', models.IntegerField(default=0, verbose_name='Costo (CLP)')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock Saldo')),
                ('stock_critical', models.IntegerField(default=5, verbose_name='Stock Crítico')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado el')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('movement_type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida'), ('ADJ', 'Ajuste'), ('SALE', 'Venta')], max_length=10, verbose_name='Tipo')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Razón')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
            },
        ),
    ]
