# Generated by Django 6.0.2 on 2026-02-18 18:57 (manually fixed)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_make_tenant_nonnull'),
        ('tenants', '0002_default_tenant'),
    ]

    operations = [
        # 1. Rename existing CharField 'brand' → 'brand_name' (preserves data)
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='brand_name',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Marca (legacy)'),
        ),

        # 2. Create Brand and Supplier models FIRST (before FK references)
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado el')),
                ('name', models.CharField(max_length=100, verbose_name='Marca')),
                ('logo', models.ImageField(blank=True, upload_to='brands/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='Tienda')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado el')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre Proveedor')),
                ('rut', models.CharField(blank=True, max_length=12, verbose_name='RUT Proveedor')),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='Contacto')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='Tienda')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'unique_together': {('tenant', 'rut')},
            },
        ),

        # 3. Now add FK references (Brand and Supplier exist at this point)
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.brand', verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.supplier', verbose_name='Proveedor'),
        ),

        # 4. Other new Product fields
        migrations.AddField(
            model_name='product',
            name='bulk_price_per_kg',
            field=models.IntegerField(blank=True, null=True, verbose_name='Precio por Kg (granel)'),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_clp',
            field=models.IntegerField(default=0, verbose_name='Costo Neto (CLP)'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_margin_pct',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Margen Mínimo (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_stock_alert',
            field=models.DecimalField(decimal_places=3, default=5, max_digits=10, verbose_name='Stock Mínimo (alerta)'),
        ),
        migrations.AddField(
            model_name='product',
            name='protein',
            field=models.CharField(choices=[('CHICKEN', 'Pollo'), ('BEEF', 'Res'), ('SALMON', 'Salmón'), ('LAMB', 'Cordero'), ('DUCK', 'Pato'), ('PORK', 'Cerdo'), ('MIXED', 'Mix/Varios'), ('VEGGIE', 'Vegetariano'), ('NONE', 'N/A')], default='NONE', max_length=10, verbose_name='Proteína Principal'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso Envase (Kg)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='species',
            field=models.CharField(choices=[('DOG', 'Perro'), ('CAT', 'Gato'), ('BIRD', 'Ave'), ('FISH', 'Pez'), ('RODENT', 'Roedor'), ('REPTILE', 'Reptil'), ('OTHER', 'Exótico/Otro')], default='DOG', max_length=10, verbose_name='Especie'),
        ),
    ]
