# Generated by Django 6.0.2 on 2026-02-16 15:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_pet_name_remove_customer_pet_type_and_more'),
        ('inventory', '0002_rename_price_product_price_clp_remove_category_slug_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='total_clp',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='amount_clp',
        ),
        migrations.RemoveField(
            model_name='order',
            name='note',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha Venta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Pagado'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='line_total_clp',
            field=models.IntegerField(default=0, verbose_name='Total Línea (CLP)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_price_clp',
            field=models.IntegerField(default=0, verbose_name='Precio Unitario (CLP)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta (Redcompra)'), ('TRANSFER', 'Transferencia')], max_length=20),
        ),
    ]
