# Generated by Django 6.0.2 on 2026-02-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_last_4',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Últimos 4 Dígitos Tarjeta'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Transacción / Nro Operación'),
        ),
    ]
